# -*- coding: utf-8 -*-
"""playstore.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mwptzijyYVdEjt_nmQ7fodQ5APD0RHib
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('/content/drive/MyDrive/dataset/dataset/Training_Data_Google_Play_reviews_6000.csv')
df.head()

df.shape

df.columns

df = df.drop(['thumbsUpCount','reviewCreatedVersion','replyContent','repliedAt'], axis = 1)
df.head()

df.info()

df.drop_duplicates(inplace = True)
df.shape

df['content'].unique()

df.info()

df['app_id'].unique()

df['reviewId'].unique()

df.head()

df['userLang'].unique()

df['userImage'].unique()

"""**visualization**"""

!pip install --upgrade seaborn
import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize = (16,10))
ax = sns.countplot(x='score', data=df) # Use countplot instead of counterplot and specify the data source
plt.xticks(rotation=90)
plt.show()

!pip install --upgrade seaborn
import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize = (16,10))
ax = sns.countplot(x='userLang', data=df) # Use countplot instead of counterplot and specify the data source
plt.xticks(rotation=90)
plt.show()

!pip install --upgrade seaborn
import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize = (16,10))
ax = sns.countplot(x='app_id', data=df) # Use countplot instead of counterplot and specify the data source
plt.xticks(rotation=90)
plt.show()

!pip install --upgrade seaborn
import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize = (16,10))
ax = sns.countplot(x='content', data=df) # Use countplot instead of counterplot and specify the data source
plt.xticks(rotation=90)
plt.show()